/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

import datos.Ventas_DB;
import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Frame.NORMAL;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import negocio.Producto;

/**
 *
 * @author JAMS
 */
public class Elegir_ProductoVentas extends javax.swing.JFrame {
    

    
    private DefaultTableModel tabla;
    private int columna;
    private int opc;
    
    
    private Ventas vpro;
    private Connection con;
    /**
     * Creates new form Elegir_Producto
     */
    public Elegir_ProductoVentas(Ventas p,Connection con) throws SQLException {
        initComponents();
        
        this.con=con;
        this.opc=opc;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        creaciontabla();
        this.vpro=p;
        
       
    }
    
    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("img/icono.png"));


       return retValue;
    }
    
     public void creaciontabla() throws SQLException
    {
        
        this.tabla=(DefaultTableModel) this.tbdatos.getModel();

        this.tabla.setRowCount(0);
        
        Ventas_DB db = new Ventas_DB(this.con);
        
        List<Producto> pro = db.select_prod();
        for (int i = 0; i < pro.size(); i++) {    
            Object[] obj = new Object[5];
            obj[0]=pro.get(i).getId();
            obj[1]=pro.get(i).getClave();
            obj[2]=pro.get(i).getNombre();
            obj[3]=pro.get(i).getPventa();
            obj[4]=pro.get(i).getIva();
            this.tabla.addRow(obj);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtdescuento = new javax.swing.JTextField();
        lbcantidad = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        lbcantidad1 = new javax.swing.JLabel();
        txtcomision = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(162, 127, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 11, -1, 39));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Clave", "Nombre", "Precio", "Iva"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbdatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbdatos.setColumnSelectionAllowed(true);
        tbdatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbdatos.setGridColor(new java.awt.Color(204, 204, 204));
        tbdatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbdatos.setShowHorizontalLines(false);
        tbdatos.setShowVerticalLines(false);
        tbdatos.getTableHeader().setReorderingAllowed(false);
        tbdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatos);
        tbdatos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tbdatos.getColumnModel().getColumnCount() > 0) {
            tbdatos.getColumnModel().getColumn(0).setPreferredWidth(35);
            tbdatos.getColumnModel().getColumn(1).setPreferredWidth(70);
            tbdatos.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 490, 240));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Buscar  :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        txtbuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        jPanel2.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 230, -1));

        txtid.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtid.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtid.setEnabled(false);
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 147, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("ID Producto :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Clave :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        txtclave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtclave.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtclave.setEnabled(false);
        jPanel2.add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 147, -1));

        txtnombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtnombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnombre.setEnabled(false);
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 240, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Nombre Producto :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Descuento :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        txtdescuento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(txtdescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 200, -1));

        lbcantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbcantidad.setText("Cantidad :");
        lbcantidad.setToolTipText("");
        jPanel2.add(lbcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        txtcantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidadKeyReleased(evt);
            }
        });
        jPanel2.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 200, -1));

        btnAceptar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 130, -1));

        lbcantidad1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbcantidad1.setText("Comision : ");
        lbcantidad1.setToolTipText("");
        jPanel2.add(lbcantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        txtcomision.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtcomision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcomisionKeyReleased(evt);
            }
        });
        jPanel2.add(txtcomision, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 200, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 880, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(this.tabla);
        this.tbdatos.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(this.txtbuscar.getText().toUpperCase(),2));
    }//GEN-LAST:event_txtbuscarKeyReleased

    public boolean validad_vacio()
    {
        boolean pasa=true;
        
        if (this.txtdescuento.getText().isEmpty()) {
            this.txtdescuento.setText("0");
        }
            
        if (this.txtcantidad.getText().isEmpty()) {
            pasa=false;
            this.txtcantidad.setBackground(Color.decode("#FFCCCC"));
        }

        if (this.txtcomision.getText().isEmpty()) {
            pasa=false;
            this.txtcomision.setBackground(Color.decode("#FFCCCC"));
        }
        
        return pasa;
           
    }

    public boolean validad_formato()
    {
        boolean pasa=true;
        String error="";
        
        if (!this.txtdescuento.getText().matches("^[0-9]*(.[0-9]+)?$")) {
            pasa=false;
            this.txtdescuento.setBackground(Color.decode("#FFCCCC"));
            error+="Descuento: 10.5 ó 50\n";
        }
            
        if (!this.txtcantidad.getText().matches("^[0-9]*(.[0-9]+)?$")) {
            pasa=false;
            this.txtcantidad.setBackground(Color.decode("#FFCCCC"));
            error+="Cantidad: 10.5 ó 50\n";
        }

        if (!this.txtcomision.getText().matches("^[0-9]*(.[0-9]+)?$")) {
            pasa=false;
            this.txtcomision.setBackground(Color.decode("#FFCCCC"));
            error+="Comision: 10.5 ó 50\n";
        }
        if (!pasa) {
            JOptionPane.showMessageDialog(null, "Formato invalido:\n"+error);
        }
        return pasa;
           
    }
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try{
          
            boolean valida=true;
   
            if (validad_vacio()) {
                if (validad_formato()) {
                    String[] c = new String[8];
                
                    c[0]=this.txtid.getText();
                    c[1]=this.txtclave.getText();
                    c[2]=this.txtnombre.getText();
                    c[3]=this.txtdescuento.getText();
                    c[4]=this.txtcantidad.getText();
                    c[5]=this.txtcomision.getText();
                    c[6]=this.tbdatos.getValueAt(this.columna, 3).toString();
                    c[7]=this.tbdatos.getValueAt(this.columna, 4).toString();
                    this.vpro.colocarproducto(c);
                    this.vpro.setEnabled(true);
                    this.vpro.setState(NORMAL);
                    this.dispose();
                }
                
            }
            else
            {
               JOptionPane.showMessageDialog(null, "Campos vacios");
            }
            
        
        } 
        catch (Exception ex) {
                Logger.getLogger(Elegir_ProductoVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         this.vpro.setEnabled(true);
         this.vpro.setState(NORMAL);
    }//GEN-LAST:event_formWindowClosing

    private void tbdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatosMouseClicked
        try
        {
            this.columna=this.tbdatos.getSelectedRow();

            this.txtid.setText(this.tbdatos.getValueAt(this.columna, 0).toString());
            this.txtclave.setText(this.tbdatos.getValueAt(this.columna, 1).toString());
            this.txtnombre.setText(this.tbdatos.getValueAt(this.columna, 2).toString());
           
            this.btnAceptar.setEnabled(true);
            this.txtcantidad.setEnabled(true);
        }
        catch(Exception ex)
        {

        }
    }//GEN-LAST:event_tbdatosMouseClicked

    public void regresar_color(JTextField jx)
    {
        jx.setBackground(Color.WHITE);
    }
    
    private void txtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyReleased
        regresar_color(txtcantidad);
    }//GEN-LAST:event_txtcantidadKeyReleased

    private void txtcomisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomisionKeyReleased
        regresar_color(txtcomision);
    }//GEN-LAST:event_txtcomisionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elegir_ProductoVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elegir_ProductoVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elegir_ProductoVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elegir_ProductoVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                   // new Elegir_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcantidad;
    private javax.swing.JLabel lbcantidad1;
    private javax.swing.JTable tbdatos;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtcomision;
    private javax.swing.JTextField txtdescuento;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
